### ISSUE TITLE
OpenTabletDriver should not be run with administrator privileges

### ISSUE THREAD

**Issue by mazzu** [InfinityGhost/OpenTabletDriver#681]
I'm on Windows and using the only user i have set up, which has administrator privileges. When opening the UI (not the daemon or the installer) I get this error "OpenTabletDriver should not be run with administrator privileges".

I looked in every .exe's file properties and "run as administrator" is unchecked under the "compatibility" tab.
This is happening since 0.5.0 update.

![image](https://user-images.githubusercontent.com/2535796/105149637-0a8de400-5b04-11eb-8006-ed11ea85ba9f.png)

**Comment by jjhhgg100123** [comment]
Send us a picture of the UAC Control Settings page, just for confirmation. It has a slider to adjust the setting.

**Comment by KissMyUSSR** [comment]
Just got exactly the same problem.

**Comment by mazzu** [comment]
I too have the option set to "never notify"
![image](https://user-images.githubusercontent.com/2535796/105160422-842bcf00-5b10-11eb-8b9f-0b3a3ea4c26e.png)

**Comment by mazzu** [comment]
I too have the option set to "never notify". 

![image](https://user-images.githubusercontent.com/2535796/105160422-842bcf00-5b10-11eb-8b9f-0b3a3ea4c26e.png)

Changing to default fixed it, but anyway it doesn't prompt me anything so I don't get it. Also what if I want to leave it to "never notify"?

**Comment by KissMyUSSR** [comment]
Yup, changing it to default fixed it but I want to keep it on never. So, could you please fix that. Very appreciated for your work.

**Comment by AbstractQbit** [comment]
Having UAC disabled is essentially equivalent to running absolutely everything as root on UNIX-like systems. If the latter is frowned upon as being a security nightmare, why would that not be the case in Windows world?

Anyway, that error will probably get swapped to a warning in an upcoming hotfix, but you still shouldn't have UAC disabled regardless.

**Comment by mazzu** [comment]
In fact I was just second-guessing my choice, I don't know enough of Windows about user permissions, also I thought that only executables which explicitly runs as admin were given special privileges, not everything. If that's the case maybe the best practice is using a normal user on windows like it's done on UNIX?

Anyway I digress, thank you for the awesome work!

**Comment by AbstractQbit** [comment]
Back in Windows XP, if your account was an admin, everything you ran had all administrative permissions. That was a problem because people used those accounts for everyday stuff, when that was not what they were designed for. 

In Windows Vista Microsoft added UAC to tackle that giant security hole. What it does is it makes a second unpriviledged account for every administrative one behind the scenes, and runs programs with it. If a program depends on administrative access, then UAC prompts user whether that program is trusted enough to be ran as admin.

By disabling that feature everything starts working the way it used to in XP days, ie really insecurely.

And yes, you are absolutely correct, having a separate user account for everyday use and elevating to admin by typing a password in UAC is indeed the safest way to use your system.

**Comment by InfinityGhost** [comment]
FWIW, we're gonna change this prompt just to warn users that there are potential issues with OTD by running without UAC or as an administrator.

**Comment by adxv** [comment]
Workaround: Create a bat file with the following command:
runas /trustlevel:0x20000 C:\Users\adams\Downloads\OpenTabletDriver.Installer.exe
